apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vpa-recommender-swapi-dev
  namespace: querium-swapi
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       swapi-dev
  updatePolicy:
    updateMode: "Auto"
