#------------------------------------------------------------------------------
# written by: Lawrence McDaniel
#             https://lawrencemcdaniel.com
#
# date:       sep-2022
# usage:      blah
#------------------------------------------------------------------------------
name: Deploy SWAPI to Kubernetes
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  environment-id:
    description: 'The SWAPI platform environment. Examples: dev, prod'
    required: true
    type: string
  namespace:
    description: 'The Kubernetes namespace to which the SWAPI platform environment will be deployed. Example: querium-swapi'
    required: true
    type: string

runs:
  using: "composite"
  steps:
    # ---------------------------------------------------------------------------------
    # Configure k8s add-on resources
    #
    # note that the Kubernetes additional config data is locally
    # stored in ci/deploy/environments/prod/k8s/
    # in Kubernetes manifest yaml format
    # ---------------------------------------------------------------------------------
    - name: set environment variables
      shell: bash
      run: |-
        echo "EXAMPLE_ENVIRONMENT_VARIABLE=$(echo 'hello world')" >> $GITHUB_ENV


    - name: Apply Kubernetes manifests
      shell: bash
      run:  |-
        # Create kubernetes deployment, ingress and other resources
        kubectl apply -f "ci/deploy/environments/${{ inputs.environment-id }}/k8s"

    #------------------------------------------------------------------------
    # IV. Merge all of the configuration data
    #
    # In this step we're combining three sources of data:
    # 1. sensitive configuration data retrieved from Kubernetes secrets in section II above
    # 2. SWAPI services configuration data created here in section III
    # 3. SWAPI configuration data
    #------------------------------------------------------------------------
    - name: cat settings_merge.yml
      shell: bash
      run:  cat -n $GITHUB_WORKSPACE/ci/deploy/environments/${{ inputs.environment-id }}/settings_merge.yml

    - name: Deploy SWAPI
      shell: bash
      run:  |-
        echo "deploy!"
