#------------------------------------------------------------------------------
# written by: Miguel Afonso
#             https://www.linkedin.com/in/mmafonso/
#
# date:       Aug-2021
#
# usage:      setup SSL certs for EKS load balancer worker node instances.
#             see https://cert-manager.io/docs/
#------------------------------------------------------------------------------
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: aktiv.qq-stepwise-api.querium.com
  namespace: querium-swapi
spec:
  secretName: aktiv.qq-stepwise-api-tls
  issuerRef:
    kind: ClusterIssuer
    name: aktiv.qq-stepwise-api.querium.com
  commonName: aktiv.qq-stepwise-api.querium.com
  dnsNames:
    - "aktiv.qq-stepwise-api.querium.com"
    - "*.aktiv.qq-stepwise-api.querium.com"
