apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: swapi-aktiv
  namespace: querium-swapi
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: swapi-aktiv
  maxReplicas: 10
  minReplicas: 1
  behavior:
    scaleDown:
      policies:
      - type: Pods
        value: 5
        periodSeconds: 300
      - type: Percent
        value: 20
        periodSeconds: 300
      selectPolicy: Max
      stabilizationWindowSeconds: 300
    scaleUp:
      policies:
      - type: Pods
        value: 5
        periodSeconds: 300
      - type: Percent
        value: 50
        periodSeconds: 300
      selectPolicy: Max
      stabilizationWindowSeconds: 0
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: AverageValue
        averageValue: 50m
