apiVersion: v1
kind: Service
metadata:
  name: swapi-aktiv
  namespace: querium-swapi
  labels:
    app.kubernetes.io/instance: swapi-aktiv
    app.kubernetes.io/name: swapi-aktiv
    app: swapi-aktiv
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: swapi-aktiv
  sessionAffinity: None
  type: ClusterIP
