#------------------------------------------------------------------------------
# written by: Lawrence McDaniel
#             https://lawrencemcdaniel.com
#
# date:       sep-2022
#
# usage:      initialize the Github Actions operating environment.
#             - checkout all Github repos
#             - create a session token for aws cli
#             - login to the AWS Elastic Container Registry
#             - install needed software packages
#             - initialize AWS ECR URIs
#------------------------------------------------------------------------------
name: Initialize Github Actions environment for build/deploy work flows
description: 'Initialize Github Actions environment with aws-cli, aws ecr login, install kubectl and other required system packages'
branding:
  color: 'orange'
  icon: 'cloud'
inputs:
  aws-access-key-id: 
    description: 'aws cli key'
    required: true
    type: string
  aws-secret-access-key:
    description: 'aws cli secret'
    required: true
    type: string
  aws-region:
    description: 'The AWS region in which the AWS Elastic Container Registry and EKS Kubernetes cluster are located.'
    required: false
    default: us-east-2
    type: string
  k8s-namespace:
    description: 'Example: querium-swapi'
    required: false
    default: 'querium-swapi'
    type: string
  eks-cluster-name:
    description: 'Example: stepwise-global-live'
    required: false
    default: 'stepwise-global-live'
    type: string


runs:
  using: "composite"
  steps:
    # checkout github all repos for this workflow: this repo, plus, 
    # all Gihubs Actions repos in this workflow. 
    # this is written and maintained by Github
    - name: Checkout
      uses: actions/checkout@v3.0.2

    # AWS helper method. creates a session token that's usable by all other
    # aws-actions. Prevents us from having to explicitly provide authentication credentials
    # to each aws-actions method individually.
    # This is written and maintained by AWS.
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1.7.0
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    # Setup a connection to our AWS Elastic Container Registry so that we can pull
    # containers that we created with the build workflows in this Cookiecutter.
    # this is written and maintained by AWS.
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # Open edX Github Actions init procedure. Provides reliable initializations of
    # kubectl, aws-cli and tutor.
    # this is written and maintained by Lawrence McDaniel + the Open edX devops community
    - name: Initialize environment
      uses: openedx-actions/tutor-k8s-init@v1.0.4
      with:
        eks-cluster-name: ${{ inputs.eks-cluster-name }}
        aws-region: ${{ inputs.aws-region }}

    - name: Create k8s namespace if it does not exist
      id: create-namespace
      shell: bash
      run: |-
        kubectl create namespace ${{ inputs.eks-cluster-name }} --dry-run=client -o yaml | kubectl apply -f -
