#------------------------------------------------------------------------------
# written by: Lawrence McDaniel
#             https://lawrencemcdaniel.com
#
# date:       sep-2022
#
# usage:      top-level workflow. Initiated manually from Github Actions console page
#             - Build the Docker container
#             - upload to AWS ECR
#             - tag as latest.
#------------------------------------------------------------------------------
name: Build Querium SWAPI dev

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-2
      ENVIRONMENT_ID: dev
      REPOSITORY: querium/swapi-dev
    steps:
      - name: Intialize AWS ECR repo URIs
        shell: bash
        run: |-
          echo "AWS_ECR_REPOSITORY_SWAPI=${AWS_ECR_URI}/querium/swapi-${{ env.ENVIRONMENT_ID }}" >> $GITHUB_ENV

      #------------------------------------------------------------------------
      # Initialize our Ubuntu environment using a common Action stored in this
      # repository
      #------------------------------------------------------------------------
      - name: Initialize environment
        uses: ./.github/actions/init
        with:
          aws-region: ${{ env.AWS_REGION }}

      # verify that the ECR repository exists. If not, then create it.
      # written and maintained by Lawrence McDaniel
      - name: Create the AWS ECR repository
        id: create-repository
        uses: lpm0073/aws-ecr-create@v0.1.1
        with:
          aws-ecr-repository: '${{ env.REPOSITORY }}-${{ env.ENVIRONMENT_ID }}'

      # Derive the three components of the AWS ECR URI
      # - AWS_ECR_REGISTRY_SWAPI: 320713933456.dkr.ecr.us-east-2.amazonaws.com
      # - AWS_ECR_REPOSITORY_SWAPI: querium/swapi-dev
      # - REPOSITORY_TAG_SWAPI: 202209162127
      - name: Intialize environment variables
        id: init-env
        shell: bash
        run: |
          echo "AWS_ECR_REGISTRY_SWAPI=${{ steps.login-ecr.outputs.registry }}" >> $GITHUB_ENV
          echo "AWS_ECR_REPOSITORY_SWAPI='${{ env.REPOSITORY }}-${{ env.ENVIRONMENT_ID }}'" >> $GITHUB_ENV
          echo "REPOSITORY_TAG_SWAPI=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV

      # create the AWS ECR URI
      # example: 320713933456.dkr.ecr.us-east-2.amazonaws.com/querium/swapi-dev:202209162127
      - name: Initialize Docker image URI
        id: init-docker-image
        shell: bash
        run: |
          echo "DOCKER_IMAGE_SWAPI=${AWS_ECR_REGISTRY_SWAPI}/${AWS_ECR_REPOSITORY_SWAPI}:${REPOSITORY_TAG_SWAPI}" >> $GITHUB_ENV
          echo "DOCKER_IMAGE_SWAPI_LATEST=${AWS_ECR_REGISTRY_SWAPI}/${AWS_ECR_REPOSITORY_SWAPI}:latest" >> $GITHUB_ENV

      - name: Build the image
        id: tutor-build-image
        shell: bash
        run: |-
          echo "build the Docker image"
          docker build . -t ${DOCKER_IMAGE_SWAPI}

      - name: Push the image
        id: docker-push-image
        shell: bash
        run: |-
          echo "push the Docker image"
          docker tag ${DOCKER_IMAGE_SWAPI} ${DOCKER_IMAGE_SWAPI_LATEST}
          docker push ${DOCKER_IMAGE_SWAPI_LATEST}
